CREATE DATABASE retail_analytics;
USE retail_analytics;

CREATE TABLE sales (
    row_id INT,
    order_id VARCHAR(20),
    order_date DATE,
    ship_date DATE,
    ship_mode VARCHAR(20),
    customer_id VARCHAR(20),
    customer_name VARCHAR(50),
    segment VARCHAR(20),
    country VARCHAR(30),
    city VARCHAR(30),
    state VARCHAR(30),
    postal_code VARCHAR(10),
    region VARCHAR(10),
    product_id VARCHAR(20),
    category VARCHAR(30),
    sub_category VARCHAR(30),
    product_name VARCHAR(200),
    sales DECIMAL(10,4),
    year INT,
    month INT,
    month_name VARCHAR(5)
);

SELECT COUNT(*) FROM sales_data_cleaned;

-- Query 1: What is the total revenue generated by the store?
SELECT ROUND(SUM(Sales), 2) AS Total_Revenue
FROM sales_data_cleaned;

-- Query 2 — What is the average revenue per order?
SELECT ROUND(AVG(Sales), 2) AS Average_Order_Value
FROM sales_data_cleaned;

-- Query 3 — Which product category generates the most revenue?
SELECT Category, ROUND(SUM(Sales), 2) AS Total_Revenue
FROM sales_data_cleaned
GROUP BY Category
ORDER BY Total_Revenue DESC;

-- Query 4 — Which are the top 10 cities by sales?
SELECT City, ROUND(SUM(Sales), 2) AS Total_Sales
FROM sales_data_cleaned
GROUP BY City
ORDER BY Total_Sales DESC
LIMIT 10;

-- Query 5 — How does revenue change month by month?
SELECT Month, Month_Name, ROUND(SUM(Sales), 2) AS Monthly_Revenue
FROM sales_data_cleaned
GROUP BY Month, Month_Name
ORDER BY Month ASC;

-- Query 6 — Which year had the highest sales?
SELECT Year, ROUND(SUM(Sales), 2) AS Yearly_Revenue
FROM sales_data_cleaned
GROUP BY Year
ORDER BY Yearly_Revenue DESC;

-- Query 7 — Which are the top 10 products by revenue?
SELECT `Product ID`, ROUND(SUM(Sales), 2) AS Total_Revenue
FROM sales_data_cleaned
GROUP BY `Product ID`
ORDER BY Total_Revenue DESC
LIMIT 10;

-- Query 8 — Which region performs the best in terms of sales?
SELECT Region, ROUND(SUM(Sales), 2) AS Total_Sales
FROM sales_data_cleaned
GROUP BY Region
ORDER BY Total_Sales DESC;

-- Query 9 — Which customer segment generates the most revenue?
SELECT Segment, ROUND(SUM(Sales), 2) AS Total_Sales
FROM sales_data_cleaned
GROUP BY Segment
ORDER BY Total_Sales DESC;

-- Query 10 — Which shipping mode is used the most?
SELECT `Ship Mode`, COUNT(*) AS Total_Orders
FROM sales_data_cleaned
GROUP BY `Ship Mode`
ORDER BY Total_Orders DESC;

-- Query 11 — Which month has the highest sales overall?
SELECT Month_Name, ROUND(SUM(Sales), 2) AS Total_Sales
FROM sales_data_cleaned
GROUP BY Month_Name
ORDER BY Total_Sales DESC
LIMIT 1;

-- Query 12 — What is the total number of orders placed?
SELECT COUNT(DISTINCT `Order ID`) AS Total_Orders
FROM sales_data_cleaned;

USE retail_analytics;